CREATE TABLE IF NOT EXISTS users (
  id BIGSERIAL PRIMARY KEY, name VARCHAR(100) NOT NULL, email VARCHAR(150) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL, phone VARCHAR(15), role VARCHAR(20) NOT NULL DEFAULT 'USER',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS stations (
  id BIGSERIAL PRIMARY KEY, name VARCHAR(100) NOT NULL, code VARCHAR(20) UNIQUE NOT NULL,
  line VARCHAR(100), station_order INTEGER, active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS tickets (
  id BIGSERIAL PRIMARY KEY, ticket_number VARCHAR(50) UNIQUE NOT NULL,
  user_id BIGINT NOT NULL REFERENCES users(id),
  source_station_id BIGINT NOT NULL REFERENCES stations(id),
  destination_station_id BIGINT NOT NULL REFERENCES stations(id),
  passenger_count INTEGER NOT NULL CHECK (passenger_count > 0),
  fare_per_passenger DECIMAL(10,2) NOT NULL, total_fare DECIMAL(10,2) NOT NULL,
  booking_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, journey_date DATE NOT NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'BOOKED' CHECK (status IN ('BOOKED','CANCELLED','COMPLETED')));
CREATE INDEX IF NOT EXISTS idx_tickets_user ON tickets(user_id);
CREATE INDEX IF NOT EXISTS idx_tickets_status ON tickets(status);
CREATE INDEX IF NOT EXISTS idx_tickets_journey ON tickets(journey_date);
